// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WASMFAQv2.Server.Contexts;

#nullable disable

namespace WASMFAQv2.Migrations
{
    [DbContext(typeof(FAQContext))]
    [Migration("20250506050138_added-sort-order")]
    partial class Addedsortorder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WASMFAQv2.Shared.Models.QnA", b =>
                {
                    b.Property<int>("QnaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QnaId"));

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<int?>("QnASetId")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("QnaId");

                    b.HasIndex("QnASetId");

                    b.ToTable("QnAs");
                });

            modelBuilder.Entity("WASMFAQv2.Shared.Models.QnASet", b =>
                {
                    b.Property<int>("QnASetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QnASetId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("QnASetId");

                    b.ToTable("QnASets");
                });

            modelBuilder.Entity("WASMFAQv2.Shared.Models.QnA", b =>
                {
                    b.HasOne("WASMFAQv2.Shared.Models.QnASet", null)
                        .WithMany("QnAs")
                        .HasForeignKey("QnASetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WASMFAQv2.Shared.Models.QnASet", b =>
                {
                    b.Navigation("QnAs");
                });
#pragma warning restore 612, 618
        }
    }
}
